-- ============================================================================
-- Seed the synthetic demo population Discover browses
-- ============================================================================
-- Discover only demonstrates anything with a populated deck: an empty browse
-- grid hides every layout, filter, and empty-state bug the hackathon exists to
-- find. These 65 members and 18 organizations are the demo population.
--
-- ---------------------------------------------------------------------------
-- Where this data comes from, and where it does not
-- ---------------------------------------------------------------------------
-- Every row here was generated mechanically from `MEMBERS` and `ORGS` in
-- src/mocks/seed.ts — the fixtures this repo has already vetted under
-- docs/PII.md: intentionally fake-sounding names, reserved `+1555` phone
-- numbers, city-center locations only. Nothing was hand-written, nothing was
-- invented, and nothing was imported from outside this repo. docs/PII.md is
-- binding and unambiguous on the alternative: no real roster, no real names, no
-- real photos, and a public org page is not consent to appear here.
--
-- The generator was a throwaway script that imported src/mocks/seed.ts and
-- printed these statements; it lives outside the repo on purpose, because the
-- fixture file is the source of truth and a second copy of the transform would
-- just be a second thing to drift.
--
-- ---------------------------------------------------------------------------
-- Ids, and why re-running this is safe
-- ---------------------------------------------------------------------------
-- The fixtures key on strings like `p_001`; `members.id` is a uuid. Each mock
-- id is mapped to a uuid derived from md5('ab-peers:member:' || mock_id) and
-- emitted as a literal, so the same fixture row always becomes the same uuid.
-- With `on conflict (id) do nothing`, re-running this migration against a
-- database that already has it is a no-op rather than a duplicate deck, and a
-- later migration can still address a specific demo member by id.
--
-- These uuids are not auth user ids and never will be — which is exactly why
-- the previous migration dropped the `auth.users` foreign key. It also means
-- every `members` RLS policy (`auth.uid() = id`) rejects writes to these rows
-- for every caller: the demo population is readable through `browse_members`
-- and writable by nobody.
--
-- ---------------------------------------------------------------------------
-- Two details worth stating
-- ---------------------------------------------------------------------------
-- `phone` is inserted because the column is `not null` and because the fixture
-- numbers are reserved 555 numbers that cannot route anywhere. It is still
-- absent from `browse_members`, so no client ever sees it.
-- `birth_date` is likewise `not null` and comes straight from the fixture; it
-- exists for the under-18 gate only and is also excluded from the view, with
-- every UI surface reading `age_band` instead (PRD §6.2).
--
-- Organizations are seeded first, from `ORGS`, keyed by slug — the same slugs
-- that members carry in `affiliations` and `verified_by`. Without them the org
-- filter chip and the "verified by" badge would render slugs with nothing
-- behind them. `logo_url` is null here: the fixtures do not carry logos, and
-- `on conflict (slug) do nothing` means the real NorCal SCI row seeded in
-- 20260819120000_organizations.sql keeps the logo it already has.
-- ============================================================================

insert into public.organizations (slug, name, logo_url) values
  ('craig-hospital', 'Craig Hospital', null),
  ('norcal-sci', 'NorCal SCI', null),
  ('christopher-dana-reeve-foundation', 'Christopher & Dana Reeve Foundation', null),
  ('triumph-foundation', 'Triumph Foundation', null),
  ('ability360', 'Ability360', null),
  ('kelly-brush-foundation', 'Kelly Brush Foundation', null),
  ('lionheart-community', 'Lionheart Community', null),
  ('borp', 'BORP', null),
  ('high-fives-foundation', 'High Fives Foundation', null),
  ('achieve-tahoe', 'Achieve Tahoe', null),
  ('bay-area-association-of-disabled-s', 'Bay Area Association of Disabled Sailors', null),
  ('santa-clara-valley-medical-center-', 'Santa Clara Valley Medical Center SCI Peer Support', null),
  ('shepherd-center', 'Shepherd Center', null),
  ('move-united', 'Move United', null),
  ('adaptive-adventures', 'Adaptive Adventures', null),
  ('angel-city-sports', 'Angel City Sports', null),
  ('disability-sports-northwest', 'Disability Sports Northwest', null),
  ('turning-point-peer-network', 'Turning Point Peer Network', null)
on conflict (slug) do nothing;

insert into public.members (
  id, type, display_name, phone, photo_url, photo_alt, avatar_color, city, state,
  disability, level, completeness, duration, duration_answered_on, years_since,
  birth_date, age_band, relationship, equipment, equipment_detail, sports_equipment,
  will_advise_on_equipment, grants, will_help_with_grants, languages, interests, topics,
  bio, employment, living, affiliations, verified_by, open_to_messages, capacity,
  show_in_browse, is_synthetic
) values
  -- p_001
  (
    '46b43f23-173c-e5cc-b13d-32345762f211'::uuid,
    'peer',
    'Neve B.',
    '+15555550101',
    null,
    null,
    '#2E5C8A',
    'Salinas',
    'California',
    'TBI',
    null,
    null,
    '10+ years',
    '2026-08-16'::date,
    30,
    '1961-08-12'::date,
    '60-69',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Dogs', 'Photography', 'Volunteering', 'Podcasts', 'Wheelchair tennis']::text[],
    '{}'::text[],
    '30 years post-injury. Manual chair. Mostly here for the dogs crowd.',
    'Part time',
    'Lives with my partner',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_002
  (
    'e92e8d56-485d-509f-1e69-4c54035f3a03'::uuid,
    'peer',
    'Elias B.',
    '+15555550102',
    null,
    null,
    '#4A4E8C',
    'Salem',
    'Oregon',
    'TBI',
    null,
    null,
    '1 - 3 years',
    '2026-08-16'::date,
    1,
    '1991-03-23'::date,
    '30-39',
    'Self',
    array['Power chair', 'Manual chair']::text[],
    'Manual chair, power chair for longer days',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['ASL', 'English']::text[],
    array['Cooking', 'Wheelchair tennis', 'Wheelchair rugby']::text[],
    '{}'::text[],
    'Trying to build a circle locally. Coffee, cooking, whatever gets me out of the house.',
    'Part time',
    'Lives with my husband',
    array['borp']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_003
  (
    'd492cf0e-3d77-3f16-85d3-7f506e3f60ec'::uuid,
    'peer',
    'Rhea S.',
    '+15555550103',
    null,
    null,
    '#0E6B5C',
    'Tacoma',
    'Washington',
    'SCI - quad',
    'C4',
    'Complete',
    '3 - 10 years',
    '2026-08-16'::date,
    5,
    '1986-10-06'::date,
    '20-29',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Scuba diving', 'Video games', 'Travel', 'Podcasts', 'Photography']::text[],
    '{}'::text[],
    '5 years post-injury. Manual chair. Mostly here for the scuba diving crowd.',
    'Full time',
    'Lives with family',
    array['norcal-sci']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_004
  (
    '2d0ba1c6-74ca-11ee-7b5e-0599ec410529'::uuid,
    'peer',
    'Ravi C.',
    '+15555550104',
    null,
    null,
    '#1B5F4E',
    'Santa Cruz',
    'California',
    'SCI - quad',
    'C6/7',
    'Incomplete',
    '10+ years',
    '2026-08-16'::date,
    12,
    '1991-05-17'::date,
    '30-39',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    array['Handcycle']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Vietnamese']::text[],
    array['Camping', 'Baking', 'Podcasts', 'Handcycling', 'Painting']::text[],
    '{}'::text[],
    'Trying to build a circle locally. Coffee, camping, whatever gets me out of the house.',
    'Full time',
    'Lives alone with a dog',
    array['borp']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_005
  (
    '45394f1e-7506-8849-23f4-461ecb7235b8'::uuid,
    'peer',
    'Paloma V.',
    '+15555550105',
    null,
    null,
    '#6B3FA0',
    'Santa Rosa',
    'California',
    'SCI - para',
    'T3',
    'Do not know',
    '10+ years',
    '2026-08-16'::date,
    20,
    '1961-12-28'::date,
    '60-69',
    'Self',
    array['Manual chair']::text[],
    'Power-assist manual chair',
    array['Monoski or sit-ski']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Portuguese']::text[],
    array['Board games', 'Swimming', 'Camping', 'Monoskiing', 'Cooking']::text[],
    '{}'::text[],
    'Getting back into board games after a long break. Always up for company.',
    'Part time',
    'Lives with my wife and two kids',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_006
  (
    '20ca4c3d-9143-2cb7-ce98-1e864caded81'::uuid,
    'peer',
    'Jonah L.',
    '+15555550106',
    null,
    null,
    '#8A5A2B',
    'Minneapolis',
    'Minnesota',
    'Spina Bifida',
    'S4',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    73,
    '1986-07-11'::date,
    '70-79',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Woodworking', 'Video games', 'Birding', 'Film & TV']::text[],
    '{}'::text[],
    '73 years post-injury. Mobility scooter. Mostly here for the woodworking crowd.',
    'Full time',
    'Lives with my parents while I finish school',
    array['borp']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_007
  (
    'b088e7c1-6eb9-ef0c-87ee-dad96e62194e'::uuid,
    'peer',
    'Bo T.',
    '+15555550107',
    null,
    null,
    '#C9491B',
    'Fort Collins',
    'Colorado',
    'MS',
    null,
    null,
    '1 - 3 years',
    '2026-08-16'::date,
    1,
    '1986-02-22'::date,
    '20-29',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Kayaking', 'Wheelchair rugby', 'Archery']::text[],
    '{}'::text[],
    '1 years in and still figuring parts of it out. Mostly here to meet people who ride.',
    'Not working',
    'Lives with my partner',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_008
  (
    'b93c275c-96b8-85c7-5112-4feca725f091'::uuid,
    'peer',
    'Callum N.',
    '+15555550108',
    null,
    null,
    '#1B5F4E',
    'Henderson',
    'Nevada',
    'Amputee',
    null,
    null,
    '10+ years',
    '2026-08-16'::date,
    24,
    '1986-09-05'::date,
    '70-79',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    array['Monoski or sit-ski']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Monoskiing', 'Film & TV', 'Swimming', 'Archery']::text[],
    '{}'::text[],
    'Getting back into monoskiing after a long break. Always up for company.',
    'Full time',
    'Lives with my husband',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_009
  (
    '93bdcb03-61bc-9f6c-340c-bfc5c8518312'::uuid,
    'peer',
    'Jonah O.',
    '+15555550109',
    null,
    null,
    '#8A5A2B',
    'Concord',
    'California',
    'TBI',
    null,
    null,
    '1 - 3 years',
    '2026-08-16'::date,
    2,
    '1986-04-16'::date,
    '20-29',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Sailing', 'Rock climbing', 'Dogs', 'Volunteering', 'Photography', 'Gardening']::text[],
    '{}'::text[],
    'Getting back into sailing after a long break. Always up for company.',
    'Full time',
    'Lives with my wife and two kids',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_010
  (
    '153921d1-d731-a044-9716-ceb28426c462'::uuid,
    'peer',
    'Maeve K.',
    '+15555550110',
    null,
    null,
    '#A8341E',
    'Boulder',
    'Colorado',
    'MS',
    null,
    null,
    '10+ years',
    '2026-08-16'::date,
    27,
    '1986-11-27'::date,
    '70-79',
    'Self',
    array['Power assist', 'Manual chair']::text[],
    'Manual chair with SmartDrive',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Travel', 'Camping', 'Woodworking', 'Painting']::text[],
    '{}'::text[],
    'New-ish to the area and looking for people to do things with on weekends.',
    'Full time',
    'Lives with my wife and two kids',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_011
  (
    '813e5ce3-6a94-36f1-0a89-b1e7ffebe913'::uuid,
    'peer',
    'Felix C.',
    '+15555550111',
    null,
    null,
    '#6B3FA0',
    'Las Vegas',
    'Nevada',
    'SCI - para',
    'T5',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    13,
    '1971-06-10'::date,
    '50-59',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Live music', 'Photography', 'Film & TV', 'Video games']::text[],
    '{}'::text[],
    'Trying to build a circle locally. Coffee, live music, whatever gets me out of the house.',
    'Student',
    'Lives with my parents while I finish school',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_012
  (
    '63cf0a3a-c0a6-008c-a51e-efe0d805483b'::uuid,
    'peer',
    'Hector F.',
    '+15555550112',
    null,
    null,
    '#14483C',
    'Ann Arbor',
    'Michigan',
    'SCI - para',
    'T11',
    'Complete',
    '3 - 10 years',
    '2026-08-16'::date,
    3,
    '1986-01-21'::date,
    '20-29',
    'Self',
    array['Manual chair']::text[],
    'Manual chair and a trail chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Birding', 'Camping', 'Photography', 'Dogs']::text[],
    '{}'::text[],
    'Trying to build a circle locally. Coffee, birding, whatever gets me out of the house.',
    'Student',
    'Lives with my partner',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_013
  (
    '8b8305e5-9b5d-ebb4-8b95-5630328749c8'::uuid,
    'peer',
    'Terrance Z.',
    '+15555550113',
    null,
    null,
    '#A8341E',
    'Chico',
    'California',
    'SCI - quad',
    'C5',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    21,
    '1981-08-04'::date,
    '40-49',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Video games', 'Road trips', 'Baking', 'Photography', 'Swimming']::text[],
    '{}'::text[],
    'Not looking for advice so much as people who get it without a long explanation.',
    'Full time',
    'Lives with my partner',
    array['norcal-sci']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_014
  (
    '5bcdbcc1-9a0b-04c5-47ce-483d08cb2659'::uuid,
    'peer',
    'Desmond S.',
    '+15555550114',
    null,
    null,
    '#C9491B',
    'Philadelphia',
    'Pennsylvania',
    'SCI - quad',
    'C7',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    27,
    '1961-03-15'::date,
    '60-69',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Podcasts', 'Board games', 'Film & TV', 'Baking', 'Swimming']::text[],
    '{}'::text[],
    'Recently moved to Philadelphia. Would love to find the local scene.',
    'Student',
    'Lives alone',
    array['borp']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_015
  (
    '649b8554-96b0-1ac7-4a63-a099d021fa91'::uuid,
    'peer',
    'Mira C.',
    '+15555550115',
    null,
    null,
    '#14483C',
    'Pittsburgh',
    'Pennsylvania',
    'SCI - para',
    'T2',
    'Complete',
    '3 - 10 years',
    '2026-08-16'::date,
    5,
    '1986-10-26'::date,
    '20-29',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    array['Handcycle']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Mandarin']::text[],
    array['Kayaking', 'Gym & fitness', 'Handcycling', 'Sled hockey', 'Fishing']::text[],
    '{}'::text[],
    'New-ish to the area and looking for people to do things with on weekends.',
    'Not working',
    'Lives with a roommate',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_016
  (
    '7fb46867-9eb3-41aa-0754-ed32a6c2a1c6'::uuid,
    'peer',
    'Nella L.',
    '+15555550116',
    null,
    null,
    '#4A4E8C',
    'Eugene',
    'Oregon',
    'MS',
    null,
    null,
    '3 - 10 years',
    '2026-08-16'::date,
    3,
    '1961-05-09'::date,
    '60-69',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    array['Handcycle', 'Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'French']::text[],
    array['Camping', 'Handcycling', 'Wheelchair rugby', 'Wheelchair tennis', 'Cooking', 'Gardening']::text[],
    '{}'::text[],
    'Injured in 2023. Happy to talk, happier to get out and do something.',
    'Full time',
    'Lives with my parents while I finish school',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_017
  (
    '2e6e5e10-f203-91c6-1408-4a1c58901ae4'::uuid,
    'peer',
    'Lena K.',
    '+15555550117',
    null,
    null,
    '#4A4E8C',
    'Boulder',
    'Colorado',
    'SCI - para',
    'L4',
    'Incomplete',
    '3 - 10 years',
    '2026-08-16'::date,
    7,
    '1961-12-20'::date,
    '60-69',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Podcasts', 'Dogs', '3D printing', 'Video games', 'Hiking with a trail chair', 'Archery']::text[],
    '{}'::text[],
    'Injured in 2019. Happy to talk, happier to get out and do something.',
    'Student',
    'Lives alone with a dog',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_018
  (
    'ac906651-144c-c092-cc19-24d085a8dfc7'::uuid,
    'peer',
    'Bianca L.',
    '+15555550118',
    null,
    null,
    '#4A4E8C',
    'Spokane',
    'Washington',
    'SCI - quad',
    'C5',
    'Do not know',
    '3 - 10 years',
    '2026-08-16'::date,
    9,
    '1986-07-03'::date,
    '20-29',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Rock climbing', 'Film & TV', 'Reading', 'Birding']::text[],
    '{}'::text[],
    '9 years in and still figuring parts of it out. Mostly here to meet people who ride.',
    'Full time',
    'Lives alone',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_019
  (
    '54536819-248a-a30d-af3b-12107a94dad8'::uuid,
    'peer',
    'Clara F.',
    '+15555550119',
    null,
    null,
    '#0E6B5C',
    'Fresno',
    'California',
    'Cerebral Palsy',
    null,
    null,
    '3 - 10 years',
    '2026-08-16'::date,
    3,
    '1986-02-14'::date,
    '20-29',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Portuguese']::text[],
    array['Rock climbing', 'Dogs', 'Woodworking', 'Kayaking']::text[],
    '{}'::text[],
    'Injured in 2023. Happy to talk, happier to get out and do something.',
    'Full time',
    'Lives alone',
    array['norcal-sci']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_020
  (
    '1a94749a-5ee1-7d58-4f83-355eefb32375'::uuid,
    'peer',
    'Silas H.',
    '+15555550120',
    null,
    null,
    '#8A5A2B',
    'Denver',
    'Colorado',
    'TBI',
    null,
    null,
    '10+ years',
    '2026-08-16'::date,
    15,
    '1981-09-25'::date,
    '40-49',
    'Self',
    array['Manual chair']::text[],
    'Power-assist manual chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Baking', 'Archery', 'Hiking with a trail chair', 'Live music']::text[],
    '{}'::text[],
    'New-ish to the area and looking for people to do things with on weekends.',
    'Retired',
    'Lives alone',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_021
  (
    '70d4ab7d-9e6d-ef1b-93ab-5d51be7178d3'::uuid,
    'peer',
    'Bo F.',
    '+15555550121',
    null,
    null,
    '#2E5C8A',
    'Philadelphia',
    'Pennsylvania',
    'Amputee',
    null,
    null,
    '10+ years',
    '2026-08-16'::date,
    15,
    '1961-04-08'::date,
    '60-69',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Painting', 'Photography', 'Sled hockey', 'Film & TV', 'Archery', 'Live music']::text[],
    '{}'::text[],
    'Getting back into painting after a long break. Always up for company.',
    'Retired',
    'Lives with my partner',
    array['triumph-foundation']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_022
  (
    '773458c4-59b0-b378-a092-fd4f5bec0f6f'::uuid,
    'peer',
    'Danae P.',
    '+15555550122',
    null,
    null,
    '#0E6B5C',
    'Santa Cruz',
    'California',
    'Cerebral Palsy',
    null,
    null,
    '1 - 3 years',
    '2026-08-16'::date,
    1,
    '1961-11-19'::date,
    '60-69',
    'Self',
    array['Manual chair']::text[],
    'Manual chair and a trail chair',
    array['Monoski or sit-ski']::text[],
    false,
    '{}'::text[],
    false,
    array['ASL', 'English']::text[],
    array['Monoskiing', 'Baking', 'Sled hockey']::text[],
    '{}'::text[],
    'Recently moved to Santa Cruz. Would love to find the local scene.',
    'Student',
    'Lives with my parents while I finish school',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_023
  (
    'e0ba4802-ea8f-afcc-9e17-7ac8939dffec'::uuid,
    'peer',
    'Quinn T.',
    '+15555550123',
    null,
    null,
    '#4A4E8C',
    'San Jose',
    'California',
    'Cerebral Palsy',
    null,
    null,
    '10+ years',
    '2026-08-16'::date,
    14,
    '1971-06-02'::date,
    '50-59',
    'Self',
    array['Power chair', 'Manual chair']::text[],
    'Manual chair, power chair for longer days',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Vietnamese']::text[],
    array['Swimming', 'Volunteering', 'Travel', 'Road trips', 'Kayaking']::text[],
    '{}'::text[],
    'Not looking for advice so much as people who get it without a long explanation.',
    'Full time',
    'Lives alone',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_024
  (
    'bcae3533-a84e-a9e9-a6c1-1e1d904927fd'::uuid,
    'peer',
    'Cyrus C.',
    '+15555550124',
    null,
    null,
    '#A8341E',
    'Tempe',
    'Arizona',
    'SCI - para',
    'L2',
    'Do not know',
    '10+ years',
    '2026-08-16'::date,
    16,
    '1971-01-13'::date,
    '50-59',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Birding', 'Hiking with a trail chair', 'Painting', 'Board games', 'Fishing', 'Gardening']::text[],
    '{}'::text[],
    'New-ish to the area and looking for people to do things with on weekends.',
    'Part time',
    'Lives with my parents while I finish school',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_025
  (
    'ca917e48-6160-e74f-db2a-3ca25812a4a6'::uuid,
    'peer',
    'Noor T.',
    '+15555550125',
    null,
    null,
    '#0E6B5C',
    'Eureka',
    'California',
    'Spina Bifida',
    'L4',
    'Do not know',
    '10+ years',
    '2026-08-16'::date,
    53,
    '1971-08-24'::date,
    '50-59',
    'Self',
    array['Manual chair']::text[],
    'Power-assist manual chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Baking', 'Board games', 'Dogs', 'Scuba diving', 'Kayaking']::text[],
    '{}'::text[],
    'Trying to build a circle locally. Coffee, baking, whatever gets me out of the house.',
    'Full time',
    'Lives with my parents while I finish school',
    array['ability360']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_026
  (
    'b3472c63-9239-6724-2b99-256828c9fdb5'::uuid,
    'peer',
    'Noor Z.',
    '+15555550126',
    null,
    null,
    '#C9491B',
    'Albany',
    'New York',
    'SCI - para',
    'T9',
    'Incomplete',
    '10+ years',
    '2026-08-16'::date,
    23,
    '1961-03-07'::date,
    '60-69',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Mandarin']::text[],
    array['Volunteering', 'Kayaking', 'Camping']::text[],
    '{}'::text[],
    'Trying to build a circle locally. Coffee, volunteering, whatever gets me out of the house.',
    'Full time',
    'Lives with my partner',
    array['triumph-foundation']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_027
  (
    'f961bb6c-2a35-d9f3-57ef-812468321218'::uuid,
    'peer',
    'Rafael P.',
    '+15555550127',
    null,
    null,
    '#6B3FA0',
    'Livermore',
    'California',
    'SCI - para',
    'T1',
    'Incomplete',
    '3 - 10 years',
    '2026-08-16'::date,
    4,
    '1981-10-18'::date,
    '40-49',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Sailing', 'Wheelchair basketball', 'Fishing', 'Painting']::text[],
    '{}'::text[],
    '4 years in and still figuring parts of it out. Mostly here to meet people who ride.',
    'Not working',
    'Lives with my parents while I finish school',
    array['norcal-sci']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_028
  (
    '47f02e56-e95f-e9c4-2af1-f67b0db5a83c'::uuid,
    'peer',
    'Desmond M.',
    '+15555550128',
    null,
    null,
    '#6B3FA0',
    'Savannah',
    'Georgia',
    'Other',
    null,
    null,
    '3 - 10 years',
    '2026-08-16'::date,
    8,
    '1986-05-01'::date,
    '20-29',
    'Self',
    array['Manual chair']::text[],
    'Manual chair and a trail chair',
    array['Monoski or sit-ski']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Vietnamese']::text[],
    array['Photography', 'Woodworking', 'Monoskiing', 'Live music']::text[],
    '{}'::text[],
    'Not looking for advice so much as people who get it without a long explanation.',
    'Full time',
    'Lives alone with a dog',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_029
  (
    '1b1ad8b7-1063-10f7-c37c-c3a871223914'::uuid,
    'peer',
    'Bea S.',
    '+15555550129',
    null,
    null,
    '#A8341E',
    'Lakewood',
    'Colorado',
    'Cerebral Palsy',
    null,
    null,
    '1 - 3 years',
    '2026-08-16'::date,
    2,
    '1971-12-12'::date,
    '50-59',
    'Self',
    array['Power assist', 'Manual chair']::text[],
    'Manual chair with SmartDrive',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Mandarin']::text[],
    array['Fishing', 'Sled hockey', 'Video games']::text[],
    '{}'::text[],
    'New-ish to the area and looking for people to do things with on weekends.',
    'Full time',
    'Lives with my husband',
    array['norcal-sci']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_030
  (
    '8006fd6d-9315-8fa8-dd50-254b94b7bfe1'::uuid,
    'peer',
    'Danae T.',
    '+15555550130',
    null,
    null,
    '#8A5A2B',
    'Minneapolis',
    'Minnesota',
    'SCI - para',
    'T7',
    'Incomplete',
    '1 - 3 years',
    '2026-08-16'::date,
    1,
    '1971-07-23'::date,
    '50-59',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    array['Monoski or sit-ski', 'Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Scuba diving', 'Reading', 'Wheelchair rugby', 'Monoskiing', 'Travel', 'Gym & fitness']::text[],
    '{}'::text[],
    '1 years post-injury. Mobility scooter. Mostly here for the scuba diving crowd.',
    'Full time',
    'Lives with my parents while I finish school',
    array['norcal-sci']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_031
  (
    'b47c7206-8a57-7031-106d-b3434d25a223'::uuid,
    'peer',
    'Bo E.',
    '+15555550131',
    null,
    null,
    '#3D5A3A',
    'Oakland',
    'California',
    'SCI - para',
    'T5',
    'Complete',
    '1 - 3 years',
    '2026-08-16'::date,
    2,
    '1971-02-06'::date,
    '50-59',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Tagalog']::text[],
    array['Road trips', 'Wheelchair tennis', 'Travel', 'Coffee', 'Camping', 'Hiking with a trail chair']::text[],
    '{}'::text[],
    'Trying to build a circle locally. Coffee, road trips, whatever gets me out of the house.',
    'Part time',
    'Lives alone with a dog',
    array['triumph-foundation']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_032
  (
    '13aba1d7-f34c-95f4-dcc5-a979ad205942'::uuid,
    'peer',
    'Marcus D.',
    '+15555550132',
    null,
    null,
    '#4A4E8C',
    'Englewood',
    'Colorado',
    'SCI - para',
    'L5',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    12,
    '1971-09-17'::date,
    '50-59',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Archery', 'Travel', 'Hiking with a trail chair', 'Rock climbing', 'Woodworking']::text[],
    '{}'::text[],
    'Trying to build a circle locally. Coffee, archery, whatever gets me out of the house.',
    'Not working',
    'Lives with family',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_033
  (
    '22d16df1-b7b7-eff9-774e-bc0b2ea44b20'::uuid,
    'peer',
    'Leo K.',
    '+15555550133',
    null,
    null,
    '#6B3FA0',
    'Portland',
    'Oregon',
    'SCI - quad',
    'C4/5',
    'Do not know',
    '1 - 3 years',
    '2026-08-16'::date,
    1,
    '1986-04-28'::date,
    '20-29',
    'Self',
    array['Power assist', 'Manual chair']::text[],
    'Manual chair with SmartDrive',
    array['Handcycle', 'Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Vietnamese']::text[],
    array['Swimming', 'Wheelchair basketball', 'Hiking with a trail chair', 'Photography', 'Handcycling']::text[],
    '{}'::text[],
    'New-ish to the area and looking for people to do things with on weekends.',
    'Full time',
    'Lives with my partner',
    array['norcal-sci']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_034
  (
    'bdaa0de1-dd72-183c-6b49-f539ba1335cf'::uuid,
    'peer',
    'Fiona N.',
    '+15555550134',
    null,
    null,
    '#2E5C8A',
    'Sunnyvale',
    'California',
    'SCI - quad',
    'C1',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    10,
    '1986-11-11'::date,
    '70-79',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    array['Monoski or sit-ski']::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Sled hockey', 'Film & TV', 'Travel', 'Archery', 'Monoskiing', 'Swimming']::text[],
    '{}'::text[],
    '10 years post-injury. Power chair. Mostly here for the sled hockey crowd.',
    'Retired',
    'Lives with my husband',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_035
  (
    'a9946277-7a48-7ab6-9bd2-ac21c0f34d82'::uuid,
    'peer',
    'Tomas V.',
    '+15555550135',
    null,
    null,
    '#A8341E',
    'Fresno',
    'California',
    'SCI - para',
    'L3',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    29,
    '1971-06-22'::date,
    '50-59',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['ASL', 'English']::text[],
    array['Reading', 'Camping', 'Volunteering', 'Live music', 'Road trips']::text[],
    '{}'::text[],
    'New-ish to the area and looking for people to do things with on weekends.',
    'Student',
    'Lives with family',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_036
  (
    '777a6425-4b09-83a4-7951-e89887f96fa4'::uuid,
    'peer',
    'Reid W.',
    '+15555550136',
    null,
    null,
    '#6B3FA0',
    'Tucson',
    'Arizona',
    'Other',
    null,
    null,
    '10+ years',
    '2026-08-16'::date,
    33,
    '1971-01-05'::date,
    '50-59',
    'Self',
    array['Manual chair']::text[],
    'Manual chair and a trail chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Korean']::text[],
    array['Photography', 'Fishing', 'Cooking', 'Live music', 'Camping']::text[],
    '{}'::text[],
    'Getting back into photography after a long break. Always up for company.',
    'Full time',
    'Lives with my partner',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_037
  (
    '14165b96-b1c5-b2e8-3910-71a7dcde25d3'::uuid,
    'peer',
    'Nadia V.',
    '+15555550137',
    null,
    null,
    '#14483C',
    'Sunnyvale',
    'California',
    'SCI - para',
    'T2',
    'Do not know',
    '1 - 3 years',
    '2026-08-16'::date,
    1,
    '1961-08-16'::date,
    '60-69',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['ASL', 'English']::text[],
    array['Film & TV', 'Fishing', 'Sled hockey', 'Podcasts', 'Photography']::text[],
    '{}'::text[],
    '1 years in and still figuring parts of it out. Mostly here to meet people who ride.',
    'Full time',
    'Lives alone with a dog',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_038
  (
    '43c4fed8-6726-b68d-c47f-c1a7c9e3c02a'::uuid,
    'peer',
    'Andre M.',
    '+15555550138',
    null,
    null,
    '#3D5A3A',
    'Tucson',
    'Arizona',
    'SCI - para',
    'T8',
    'Incomplete',
    '1 - 3 years',
    '2026-08-16'::date,
    1,
    '1991-03-27'::date,
    '30-39',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Hiking with a trail chair', 'Travel', 'Photography', 'Wheelchair basketball']::text[],
    '{}'::text[],
    'Not looking for advice so much as people who get it without a long explanation.',
    'Student',
    'Lives alone',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_039
  (
    'c26df438-090a-6333-b3ea-ee668da18111'::uuid,
    'peer',
    'Kofi G.',
    '+15555550139',
    null,
    null,
    '#A8341E',
    'Brooklyn',
    'New York',
    'SCI - quad',
    'C3',
    'Incomplete',
    '3 - 10 years',
    '2026-08-16'::date,
    9,
    '1991-10-10'::date,
    '30-39',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Volunteering', 'Painting', 'Hiking with a trail chair', 'Camping', 'Woodworking', 'Cooking']::text[],
    '{}'::text[],
    '9 years post-injury. Power chair. Mostly here for the volunteering crowd.',
    'Retired',
    'Lives alone with a dog',
    array['norcal-sci']::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- p_040
  (
    'e035d1ac-6de3-95e7-b34a-f6e8b4b125fa'::uuid,
    'peer',
    'Marcus C.',
    '+15555550140',
    null,
    null,
    '#8A5A2B',
    'San Francisco',
    'California',
    'SCI - para',
    'S1',
    'Incomplete',
    '10+ years',
    '2026-08-16'::date,
    33,
    '1961-05-21'::date,
    '60-69',
    'Self',
    array['Manual chair']::text[],
    'Power-assist manual chair',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Board games', 'Wheelchair basketball', 'Birding', 'Baking']::text[],
    '{}'::text[],
    'Recently moved to San Francisco. Would love to find the local scene.',
    'Retired',
    'Lives with my partner',
    '{}'::text[],
    null,
    false,
    null,
    true,
    true
  ),
  -- m_001
  (
    'cadd5f9f-cdbd-60ee-8ad2-025d9bb778ce'::uuid,
    'mentor',
    'Ilse V.',
    '+15555550141',
    null,
    null,
    '#1B5F4E',
    'Fort Collins',
    'Colorado',
    'N/A - family member',
    null,
    null,
    'Since birth',
    '2026-08-16'::date,
    null,
    '1971-12-04'::date,
    '50-59',
    'Family member (parent)',
    array['Prefer not to say']::text[],
    'N/A - not a wheelchair user',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Wheelchair rugby', 'Live music', 'Cooking', 'Dogs']::text[],
    array['Hiring & managing caregivers', 'Home modifications', 'SSI/SSDI & benefits', 'Going back to school', 'Grants & funding']::text[],
    'My son was injured at 19 and I was his caregiver for four years. I know the caregiver, benefits, and home-renovation side better than the medical side. Happy to talk to families.',
    'Student',
    'Lives with my husband',
    array['triumph-foundation']::text[],
    'triumph-foundation',
    true,
    'open',
    true,
    true
  ),
  -- m_002
  (
    'ee7a62ad-00f2-fc19-d572-444fc4665501'::uuid,
    'mentor',
    'Neve K.',
    '+15555550142',
    null,
    null,
    '#3D5A3A',
    'Colorado Springs',
    'Colorado',
    'Spina Bifida',
    'L4',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    58,
    '1971-07-15'::date,
    '50-59',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    array['Sport wheelchair']::text[],
    true,
    '{}'::text[],
    false,
    array['English', 'Vietnamese']::text[],
    array['Wheelchair basketball', 'Camping', 'Live music', 'Baking']::text[],
    array['Vehicle modifications', 'Pregnancy & parenting', 'Dictation & assistive tech', 'Dating & intimacy']::text[],
    'Spina Bifida since birth, so my experience is different from someone newly injured — but I''ve spent 50 years navigating benefits, equipment, and self-advocacy.',
    'Full time',
    'Lives with family',
    array['ability360']::text[],
    'ability360',
    true,
    'open',
    true,
    true
  ),
  -- m_003
  (
    '36ff8e84-63f6-932e-6728-6aacde10a25d'::uuid,
    'mentor',
    'Felix F.',
    '+15555550143',
    null,
    null,
    '#C9491B',
    'Tucson',
    'Arizona',
    'SCI - quad',
    'C6/7',
    'Do not know',
    '10+ years',
    '2026-08-16'::date,
    25,
    '1986-02-26'::date,
    '70-79',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    array['Sport wheelchair']::text[],
    true,
    array['Kelly Brush Foundation', 'Challenged Athletes Foundation']::text[],
    true,
    array['English', 'Mandarin']::text[],
    array['3D printing', 'Scuba diving', 'Wheelchair rugby']::text[],
    array['Transfers', 'SSI/SSDI & benefits', 'Choosing a wheelchair', 'Vehicle modifications', 'Aging with SCI', 'Pregnancy & parenting']::text[],
    'At capacity right now, but wave and I''ll get back to you when a slot opens.',
    'Full time',
    'Lives with my partner',
    array['borp']::text[],
    'borp',
    true,
    'at capacity',
    true,
    true
  ),
  -- m_004
  (
    'edc6fffa-c4f9-2d6c-cf50-3909f518fdba'::uuid,
    'mentor',
    'Arjun N.',
    '+15555550144',
    null,
    null,
    '#4A4E8C',
    'Boise',
    'Idaho',
    'SCI - para',
    'L1',
    'Incomplete',
    '10+ years',
    '2026-08-16'::date,
    17,
    '1991-09-09'::date,
    '30-39',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Board games', 'Rock climbing', 'Film & TV', 'Baking']::text[],
    array['Baclofen pump', 'Intermittent catheterization', 'Vehicle modifications', 'Botox', 'Hiring & managing caregivers']::text[],
    'I''ve been the person answering the phone at 2am for other peers for a long time. I don''t mind hard questions.',
    'Full time',
    'Lives alone',
    array['norcal-sci']::text[],
    'norcal-sci',
    true,
    'open',
    true,
    true
  ),
  -- m_005
  (
    'dd67437c-4176-6664-73e4-49122be42a9d'::uuid,
    'mentor',
    'Andre H.',
    '+15555550145',
    null,
    null,
    '#6B3FA0',
    'San Jose',
    'California',
    'SCI - quad',
    'C5/6',
    'Incomplete',
    '3 - 10 years',
    '2026-08-16'::date,
    8,
    '1971-04-20'::date,
    '50-59',
    'Self',
    array['Power chair', 'Manual chair']::text[],
    'Manual chair, power chair for longer days',
    array['Handcycle', 'Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Wheelchair basketball', 'Kayaking', 'Reading', 'Handcycling', 'Wheelchair rugby']::text[],
    array['Vehicle modifications', 'Grants & funding', 'Spasticity & tone', 'Service animals']::text[],
    'Manual chair, power chair for longer days. I''ve tried most of the equipment out there and can save you some expensive mistakes.',
    'Full time',
    'Lives alone',
    array['ability360', 'norcal-sci']::text[],
    'ability360',
    true,
    'paused',
    true,
    true
  ),
  -- m_006
  (
    '0cc0dc10-bce6-ec60-1f92-a3b083ddb42f'::uuid,
    'mentor',
    'Roz C.',
    '+15555550146',
    null,
    null,
    '#8A5A2B',
    'Bellingham',
    'Washington',
    'SCI - quad',
    'C4',
    'Complete',
    '3 - 10 years',
    '2026-08-16'::date,
    9,
    '1986-11-03'::date,
    '20-29',
    'Self',
    array['Manual chair']::text[],
    'Manual chair and a trail chair',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['ASL', 'English']::text[],
    array['Cooking', 'Wheelchair basketball', 'Wheelchair rugby', 'Dogs', 'Camping']::text[],
    array['Baclofen pump', 'Mental health', 'Getting back on a bike', 'SSI/SSDI & benefits']::text[],
    'Manual chair and a trail chair. Big on adaptive sports — cooking changed my life and I''d like it to change someone else''s.',
    'Full time',
    'Lives alone with a dog',
    array['norcal-sci', 'craig-hospital']::text[],
    'norcal-sci',
    true,
    'open',
    true,
    true
  ),
  -- m_007
  (
    '505872bc-8eb5-09be-4386-90a23398b9a2'::uuid,
    'mentor',
    'Neve C.',
    '+15555550147',
    null,
    null,
    '#4A4E8C',
    'Provo',
    'Utah',
    'SCI - quad',
    'C5/6',
    'Do not know',
    '10+ years',
    '2026-08-16'::date,
    24,
    '1986-06-14'::date,
    '70-79',
    'Self',
    array['Manual chair']::text[],
    'Manual chair and a trail chair',
    array['Handcycle']::text[],
    false,
    array['High Fives', 'Swim with Mike']::text[],
    false,
    array['English']::text[],
    array['Handcycling', 'Video games', 'Fishing', 'Woodworking', 'Film & TV', 'Kayaking']::text[],
    array['Choosing a wheelchair', 'Spasticity & tone', 'Hiring & managing caregivers', 'Aging with SCI']::text[],
    'Manual chair and a trail chair. I''ve tried most of the equipment out there and can save you some expensive mistakes.',
    'Full time',
    'Lives with my parents while I finish school',
    array['ability360', 'christopher-dana-reeve-foundation']::text[],
    'ability360',
    true,
    'open',
    true,
    true
  ),
  -- m_008
  (
    'bb271aff-9b6d-3b21-018c-f53556e4c7d7'::uuid,
    'mentor',
    'Simone A.',
    '+15555550148',
    null,
    null,
    '#0E6B5C',
    'Pueblo',
    'Colorado',
    'SCI - para',
    'T1',
    'Incomplete',
    '10+ years',
    '2026-08-16'::date,
    13,
    '1991-01-25'::date,
    '30-39',
    'Self',
    array['Manual chair']::text[],
    'Power-assist manual chair',
    '{}'::text[],
    true,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Rock climbing', 'Sled hockey', 'Photography', 'Coffee', 'Dogs', 'Kayaking']::text[],
    array['Choosing adaptive equipment', 'Vehicle modifications', 'Dating & intimacy', 'Suprapubic catheter', 'Pain management', 'Intermittent catheterization', 'Aging with SCI', 'Spasticity & tone']::text[],
    'Injured in 2013. Power-assist manual chair. I spent the first year thinking my life was over and it took another peer to talk me out of it — happy to be that person for someone else.',
    'Student',
    'Lives with my husband',
    array['borp']::text[],
    'borp',
    true,
    'open',
    true,
    true
  ),
  -- m_009
  (
    '6ed952a4-3e3e-45b9-dbc0-5a375dd3a362'::uuid,
    'mentor',
    'Nadia T.',
    '+15555550149',
    null,
    null,
    '#A8341E',
    'Coeur d''Alene',
    'Idaho',
    'SCI - quad',
    'C2',
    'Do not know',
    '3 - 10 years',
    '2026-08-16'::date,
    5,
    '1986-08-08'::date,
    '20-29',
    'Self',
    array['Power assist', 'Manual chair']::text[],
    'Manual chair with SmartDrive',
    '{}'::text[],
    true,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Photography', 'Gym & fitness', 'Podcasts', '3D printing', 'Reading', 'Board games']::text[],
    array['Botox', 'Hiring & managing caregivers', 'Mental health', 'Spasticity & tone', 'Moving out & living independently', 'Transfers', 'Driving & hand controls']::text[],
    '5 years in. I work in physical therapy and I get asked about returning to work more than anything else. Ask me anything, no question is too much.',
    'Full time',
    'Lives with family',
    array['craig-hospital', 'christopher-dana-reeve-foundation']::text[],
    'craig-hospital',
    true,
    'open',
    true,
    true
  ),
  -- m_010
  (
    '96338750-dd6a-0da8-4e1f-66adbc6c577a'::uuid,
    'mentor',
    'Beth M.',
    '+15555550150',
    null,
    null,
    '#A8341E',
    'Dallas',
    'Texas',
    'SCI - quad',
    'C4',
    'Incomplete',
    '10+ years',
    '2026-08-16'::date,
    15,
    '1971-03-19'::date,
    '50-59',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    '{}'::text[],
    true,
    array['Reeve Foundation Quality of Life']::text[],
    true,
    array['English']::text[],
    array['Woodworking', 'Video games', 'Baking', 'Hiking with a trail chair']::text[],
    array['Aging with SCI', 'SSI/SSDI & benefits', 'Moving out & living independently', 'Returning to work', 'Pressure sores']::text[],
    'Injured in 2011. Manual chair. I spent the first year thinking my life was over and it took another peer to talk me out of it — happy to be that person for someone else.',
    'Student',
    'Lives with my parents while I finish school',
    array['craig-hospital', 'triumph-foundation']::text[],
    'craig-hospital',
    true,
    'paused',
    true,
    true
  ),
  -- m_011
  (
    '4c28b6c4-d376-f47c-f846-8a80e7164a22'::uuid,
    'mentor',
    'Simone W.',
    '+15555550151',
    null,
    null,
    '#8A5A2B',
    'Modesto',
    'California',
    'SCI - para',
    'S3',
    'Do not know',
    '10+ years',
    '2026-08-16'::date,
    29,
    '1971-10-02'::date,
    '50-59',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    array['Sport wheelchair']::text[],
    false,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Coffee', 'Volunteering', 'Wheelchair tennis', 'Birding', 'Travel', 'Gym & fitness']::text[],
    array['Pain management', 'Travel & flying', 'Going back to school', 'UTIs', 'Spasticity & tone', 'Getting back on a bike', 'SSI/SSDI & benefits', 'Grants & funding']::text[],
    'Mobility scooter. Big on adaptive sports — coffee changed my life and I''d like it to change someone else''s.',
    'Full time',
    'Lives alone with a dog',
    array['christopher-dana-reeve-foundation', 'norcal-sci']::text[],
    'christopher-dana-reeve-foundation',
    true,
    'open',
    true,
    true
  ),
  -- m_012
  (
    '5958a6f0-933d-8f85-c9e1-a400e9651df3'::uuid,
    'mentor',
    'Malik T.',
    '+15555550152',
    null,
    null,
    '#0E6B5C',
    'Concord',
    'California',
    'Cerebral Palsy',
    null,
    null,
    '1 - 3 years',
    '2026-08-16'::date,
    1,
    '1986-05-13'::date,
    '70-79',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    '{}'::text[],
    false,
    '{}'::text[],
    false,
    array['English', 'Vietnamese']::text[],
    array['Video games', 'Photography', 'Camping', 'Woodworking']::text[],
    array['Pregnancy & parenting', 'Transfers', 'Travel & flying', 'Getting back on a bike', 'Baclofen pump', 'Going back to school']::text[],
    '1 years in. I work in construction management and I get asked about returning to work more than anything else. Ask me anything, no question is too much.',
    'Full time',
    'Lives with my wife and two kids',
    array['norcal-sci']::text[],
    'norcal-sci',
    true,
    'open',
    true,
    true
  ),
  -- m_013
  (
    '18f87d86-56f2-bdca-a16b-d97d11765644'::uuid,
    'mentor',
    'Neve V.',
    '+15555550153',
    null,
    null,
    '#3D5A3A',
    'Lakewood',
    'Colorado',
    'SCI - quad',
    'C4/5',
    'Incomplete',
    '10+ years',
    '2026-08-16'::date,
    11,
    '1981-12-24'::date,
    '40-49',
    'Self',
    array['Power chair', 'Manual chair']::text[],
    'Manual chair, power chair for longer days',
    array['Handcycle', 'Sport wheelchair']::text[],
    false,
    array['High Fives', 'State Department of Rehabilitation']::text[],
    true,
    array['English', 'Mandarin']::text[],
    array['Wheelchair basketball', 'Reading', 'Film & TV', 'Painting', 'Handcycling', 'Travel']::text[],
    array['Baclofen pump', 'Moving out & living independently', 'Pregnancy & parenting', 'Home modifications']::text[],
    'Manual chair, power chair for longer days. I''ve tried most of the equipment out there and can save you some expensive mistakes.',
    'Full time',
    'Lives with my parents while I finish school',
    array['christopher-dana-reeve-foundation', 'ability360']::text[],
    'christopher-dana-reeve-foundation',
    true,
    'open',
    true,
    true
  ),
  -- m_014
  (
    '463db064-1bb0-521b-86b4-d399246a3629'::uuid,
    'mentor',
    'Marisol G.',
    '+15555550154',
    null,
    null,
    '#8A5A2B',
    'Tampa',
    'Florida',
    'Spina Bifida',
    'L1',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    61,
    '1961-07-07'::date,
    '60-69',
    'Self',
    array['Scooter']::text[],
    'Mobility scooter',
    array['Sport wheelchair']::text[],
    true,
    array['State Department of Rehabilitation', 'Triumph Foundation']::text[],
    true,
    array['English', 'Mandarin']::text[],
    array['Reading', 'Sailing', 'Gardening', 'Board games', 'Sled hockey', 'Wheelchair basketball']::text[],
    array['Pressure sores', 'Aging with SCI', 'Home modifications', 'Dictation & assistive tech']::text[],
    'I run a small support group locally and have been at this 61 years. Bladder and bowel questions don''t faze me.',
    'Student',
    'Lives alone with a dog',
    array['triumph-foundation', 'lionheart-community']::text[],
    'triumph-foundation',
    true,
    'at capacity',
    true,
    true
  ),
  -- m_015
  (
    '67b954f1-5f0b-2102-81d1-b2d0792a4e7e'::uuid,
    'mentor',
    'Dev B.',
    '+15555550155',
    null,
    null,
    '#1B5F4E',
    'Tempe',
    'Arizona',
    'SCI - para',
    'T8',
    'Complete',
    '3 - 10 years',
    '2026-08-16'::date,
    3,
    '1971-02-18'::date,
    '50-59',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    '{}'::text[],
    true,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Sailing', 'Reading', 'Swimming', 'Gym & fitness', 'Volunteering']::text[],
    array['Travel & flying', 'Baclofen pump', 'Suprapubic catheter', 'Pressure sores', 'Botox', 'Vehicle modifications', 'Service animals']::text[],
    'I''ve been the person answering the phone at 2am for other peers for a long time. I don''t mind hard questions.',
    'Full time',
    'Lives with family',
    array['christopher-dana-reeve-foundation']::text[],
    'christopher-dana-reeve-foundation',
    true,
    'at capacity',
    true,
    true
  ),
  -- m_016
  (
    '5d0471cc-d9af-603c-f9f6-f6fd61d1776c'::uuid,
    'mentor',
    'Jonah V.',
    '+15555550156',
    null,
    null,
    '#C9491B',
    'Chico',
    'California',
    'SCI - quad',
    'C4',
    'Complete',
    '3 - 10 years',
    '2026-08-16'::date,
    6,
    '1991-09-01'::date,
    '30-39',
    'Self',
    array['Power assist', 'Manual chair']::text[],
    'Manual chair with SmartDrive',
    array['Monoski or sit-ski']::text[],
    true,
    array['VA', 'Swim with Mike']::text[],
    false,
    array['English', 'Spanish']::text[],
    array['Board games', 'Sled hockey', 'Monoskiing', 'Swimming']::text[],
    array['Hiring & managing caregivers', 'Aging with SCI', 'Choosing a wheelchair', 'Vehicle modifications']::text[],
    'Injured in 2020. Manual chair with SmartDrive. I spent the first year thinking my life was over and it took another peer to talk me out of it — happy to be that person for someone else.',
    'Full time',
    'Lives with my wife and two kids',
    array['lionheart-community']::text[],
    'lionheart-community',
    true,
    'open',
    true,
    true
  ),
  -- m_017
  (
    '9caf76da-f394-a183-c2af-54376059f328'::uuid,
    'mentor',
    'Lena A.',
    '+15555550157',
    null,
    null,
    '#2E5C8A',
    'Redding',
    'California',
    'SCI - quad',
    'C8',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    10,
    '1991-04-12'::date,
    '30-39',
    'Self',
    array['Manual chair']::text[],
    'Power-assist manual chair',
    '{}'::text[],
    true,
    array['Triumph Foundation', 'Swim with Mike', 'State Department of Rehabilitation']::text[],
    true,
    array['English']::text[],
    array['Gym & fitness', 'Photography', 'Travel', 'Reading']::text[],
    array['Aging with SCI', 'Colostomy', 'Moving out & living independently', 'Choosing a wheelchair', 'Pain management']::text[],
    'Power-assist manual chair. I''ve tried most of the equipment out there and can save you some expensive mistakes.',
    'Not working',
    'Lives with family',
    array['christopher-dana-reeve-foundation']::text[],
    'christopher-dana-reeve-foundation',
    true,
    'open',
    true,
    true
  ),
  -- m_018
  (
    'f03a718c-26f3-5720-1fde-b00983caca4a'::uuid,
    'mentor',
    'Dev H.',
    '+15555550158',
    null,
    null,
    '#0E6B5C',
    'Denver',
    'Colorado',
    'SCI - quad',
    'C7',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    24,
    '1961-11-23'::date,
    '60-69',
    'Self',
    array['Crutches or walker']::text[],
    'Walks short distances with forearm crutches',
    array['Sport wheelchair']::text[],
    true,
    array['Triumph Foundation', 'Reeve Foundation Quality of Life']::text[],
    true,
    array['English']::text[],
    array['Swimming', 'Gardening', 'Wheelchair basketball', 'Painting']::text[],
    array['Going back to school', 'Vehicle modifications', 'Getting back on a bike', 'Being injured young', 'Bowel program', 'Grants & funding']::text[],
    '24 years post-injury, two kids, full-time work. It''s doable and I''m glad to walk you through how.',
    'Full time',
    'Lives with my husband',
    array['ability360']::text[],
    'ability360',
    true,
    'open',
    true,
    true
  ),
  -- m_019
  (
    'ede32736-0a3b-503f-d81a-1c8c2971dfd9'::uuid,
    'mentor',
    'Quinn O.',
    '+15555550159',
    null,
    null,
    '#C9491B',
    'Livermore',
    'California',
    'TBI',
    null,
    null,
    '3 - 10 years',
    '2026-08-16'::date,
    8,
    '1961-06-06'::date,
    '60-69',
    'Self',
    array['Power assist', 'Manual chair']::text[],
    'Manual chair with SmartDrive',
    '{}'::text[],
    true,
    array['Challenged Athletes Foundation']::text[],
    true,
    array['English', 'Vietnamese']::text[],
    array['Painting', 'Reading', 'Baking', 'Archery', 'Coffee']::text[],
    array['Driving & hand controls', 'Transfers', 'Suprapubic catheter', 'Botox', 'Choosing a wheelchair', 'Service animals', 'Being injured young']::text[],
    'I''ve been the person answering the phone at 2am for other peers for a long time. I don''t mind hard questions.',
    'Retired',
    'Lives alone',
    array['norcal-sci', 'christopher-dana-reeve-foundation']::text[],
    'norcal-sci',
    true,
    'paused',
    true,
    true
  ),
  -- m_020
  (
    'a290abe5-e4cd-c45f-0837-6c25802dd372'::uuid,
    'mentor',
    'Beth O.',
    '+15555550160',
    null,
    null,
    '#4A4E8C',
    'Grand Rapids',
    'Michigan',
    'Amputee',
    null,
    null,
    '10+ years',
    '2026-08-16'::date,
    10,
    '1961-01-17'::date,
    '60-69',
    'Self',
    array['Manual chair']::text[],
    'Power-assist manual chair',
    array['Sport wheelchair']::text[],
    true,
    '{}'::text[],
    false,
    array['English']::text[],
    array['Wheelchair basketball', 'Archery', 'Cooking', 'Gym & fitness', 'Woodworking']::text[],
    array['Pain management', 'Mental health', 'Choosing a wheelchair', 'Colostomy', 'Returning to work', 'Aging with SCI', 'Hiring & managing caregivers', 'Dating & intimacy']::text[],
    '10 years post-injury, two kids, full-time work. It''s doable and I''m glad to walk you through how.',
    'Full time',
    'Lives with family',
    array['triumph-foundation', 'norcal-sci']::text[],
    'triumph-foundation',
    true,
    'open',
    true,
    true
  ),
  -- m_021
  (
    '551f3e2c-0981-f76d-8554-19349f519d71'::uuid,
    'mentor',
    'Fiona R.',
    '+15555550161',
    null,
    null,
    '#8A5A2B',
    'Eureka',
    'California',
    'TBI',
    null,
    null,
    '3 - 10 years',
    '2026-08-16'::date,
    3,
    '1986-08-28'::date,
    '70-79',
    'Self',
    array['Power chair', 'Manual chair']::text[],
    'Manual chair, power chair for longer days',
    array['Sport wheelchair']::text[],
    true,
    array['Swim with Mike', 'Kelly Brush Foundation']::text[],
    true,
    array['English']::text[],
    array['Swimming', 'Scuba diving', 'Archery', 'Coffee', 'Wheelchair rugby']::text[],
    array['Choosing a wheelchair', 'Grants & funding', 'Dictation & assistive tech', 'Pressure sores', 'Colostomy', 'Service animals']::text[],
    'Injured in 2023. Manual chair, power chair for longer days. I spent the first year thinking my life was over and it took another peer to talk me out of it — happy to be that person for someone else.',
    'Full time',
    'Lives with my wife and two kids',
    array['christopher-dana-reeve-foundation']::text[],
    'christopher-dana-reeve-foundation',
    true,
    'open',
    true,
    true
  ),
  -- m_022
  (
    '0d351577-6bb5-c60a-b66c-dbe6b6cccbb7'::uuid,
    'mentor',
    'Owen O.',
    '+15555550162',
    null,
    null,
    '#C9491B',
    'Fremont',
    'California',
    'SCI - para',
    'S3',
    'Complete',
    '10+ years',
    '2026-08-16'::date,
    20,
    '1971-03-11'::date,
    '50-59',
    'Self',
    array['Power assist', 'Manual chair']::text[],
    'Manual chair with SmartDrive',
    array['Sport wheelchair']::text[],
    true,
    array['Challenged Athletes Foundation', 'Reeve Foundation Quality of Life', 'High Fives']::text[],
    true,
    array['English']::text[],
    array['Swimming', 'Baking', 'Gym & fitness', 'Painting', 'Wheelchair tennis']::text[],
    array['Pregnancy & parenting', 'Dating & intimacy', 'Bowel program', 'UTIs', 'Pressure sores', 'Grants & funding', 'Intermittent catheterization']::text[],
    '20 years in. I work in logistics and I get asked about returning to work more than anything else. Ask me anything, no question is too much.',
    'Full time',
    'Lives alone',
    array['triumph-foundation', 'borp']::text[],
    'triumph-foundation',
    true,
    'at capacity',
    true,
    true
  ),
  -- m_023
  (
    '577adeed-811e-b05b-e409-6e7b16ecf0aa'::uuid,
    'mentor',
    'June Z.',
    '+15555550163',
    null,
    null,
    '#3D5A3A',
    'Livermore',
    'California',
    'SCI - quad',
    'C6',
    'Complete',
    '3 - 10 years',
    '2026-08-16'::date,
    9,
    '1971-10-22'::date,
    '50-59',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    array['Sport wheelchair']::text[],
    true,
    array['Reeve Foundation Quality of Life', 'VA', 'High Fives']::text[],
    true,
    array['English', 'Spanish']::text[],
    array['Photography', 'Archery', 'Wheelchair rugby', 'Swimming', 'Kayaking']::text[],
    array['Dating & intimacy', 'Botox', 'Suprapubic catheter', 'Intermittent catheterization', 'Pressure sores', 'Service animals', 'SSI/SSDI & benefits']::text[],
    'Injured in 2017. Manual chair. I spent the first year thinking my life was over and it took another peer to talk me out of it — happy to be that person for someone else.',
    'Student',
    'Lives alone',
    array['triumph-foundation', 'ability360']::text[],
    'triumph-foundation',
    true,
    'open',
    true,
    true
  ),
  -- m_024
  (
    '67199190-4b76-0921-3020-4d53635ef20d'::uuid,
    'mentor',
    'Anika R.',
    '+15555550164',
    null,
    null,
    '#6B3FA0',
    'Redding',
    'California',
    'SCI - quad',
    'C6',
    'Do not know',
    '10+ years',
    '2026-08-16'::date,
    12,
    '1971-05-05'::date,
    '50-59',
    'Self',
    array['Manual chair']::text[],
    'Manual chair',
    array['Handcycle']::text[],
    true,
    array['High Fives', 'VA']::text[],
    false,
    array['English', 'Vietnamese']::text[],
    array['Cooking', '3D printing', 'Sailing', 'Handcycling']::text[],
    array['Transfers', 'Pressure sores', 'SSI/SSDI & benefits', 'Botox', 'Dating & intimacy', 'Pain management']::text[],
    'Injured young, back at school within two years. If you''re in that spot right now, message me.',
    'Not working',
    'Lives with family',
    array['norcal-sci', 'craig-hospital']::text[],
    'norcal-sci',
    true,
    'open',
    true,
    true
  ),
  -- m_025
  (
    'a2517946-2f12-8a94-6807-0b48b6839ab4'::uuid,
    'mentor',
    'Elias C.',
    '+15555550165',
    null,
    null,
    '#3D5A3A',
    'Charlotte',
    'North Carolina',
    'SCI - quad',
    'C6/7',
    'Incomplete',
    '3 - 10 years',
    '2026-08-16'::date,
    3,
    '1961-12-16'::date,
    '60-69',
    'Self',
    array['Power chair']::text[],
    'Power chair',
    '{}'::text[],
    true,
    array['Challenged Athletes Foundation']::text[],
    true,
    array['English', 'Mandarin']::text[],
    array['Gardening', '3D printing', 'Camping', 'Live music']::text[],
    array['Intermittent catheterization', 'Getting back on a bike', 'Pain management', 'Vehicle modifications', 'Being injured young', 'Dictation & assistive tech', 'Grants & funding', 'Pressure sores']::text[],
    '3 years post-injury, two kids, full-time work. It''s doable and I''m glad to walk you through how.',
    'Full time',
    'Lives with my parents while I finish school',
    array['lionheart-community']::text[],
    'lionheart-community',
    true,
    'at capacity',
    true,
    true
  )
on conflict (id) do nothing;
